/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as GearRouteImport } from './routes/gear'
import { Route as LinksRouteImport } from './routes/links'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RacingRouteImport } from './routes/racing'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as GoPartnerRouteImport } from './routes/go.$partner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RacingRoute = RacingRouteImport.update({
  id: '/racing',
  path: '/racing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const GoPartnerRoute = GoPartnerRouteImport.update({
  id: '/go/$partner',
  path: '/go/$partner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/contact': typeof ContactRoute
  '/garage': typeof GarageRoute
  '/gear': typeof GearRoute
  '/links': typeof LinksRoute
  '/partners': typeof PartnersRoute
  '/racing': typeof RacingRoute
  '/results': typeof ResultsRoute
  '/sponsors': typeof SponsorsRoute
  '/watch': typeof WatchRoute
  '/go/$partner': typeof GoPartnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/contact': typeof ContactRoute
  '/garage': typeof GarageRoute
  '/gear': typeof GearRoute
  '/links': typeof LinksRoute
  '/partners': typeof PartnersRoute
  '/racing': typeof RacingRoute
  '/results': typeof ResultsRoute
  '/sponsors': typeof SponsorsRoute
  '/watch': typeof WatchRoute
  '/go/$partner': typeof GoPartnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/contact': typeof ContactRoute
  '/garage': typeof GarageRoute
  '/gear': typeof GearRoute
  '/links': typeof LinksRoute
  '/partners': typeof PartnersRoute
  '/racing': typeof RacingRoute
  '/results': typeof ResultsRoute
  '/sponsors': typeof SponsorsRoute
  '/watch': typeof WatchRoute
  '/go/$partner': typeof GoPartnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builds'
    | '/contact'
    | '/garage'
    | '/gear'
    | '/links'
    | '/partners'
    | '/racing'
    | '/results'
    | '/sponsors'
    | '/watch'
    | '/go/$partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builds'
    | '/contact'
    | '/garage'
    | '/gear'
    | '/links'
    | '/partners'
    | '/racing'
    | '/results'
    | '/sponsors'
    | '/watch'
    | '/go/$partner'
  id:
    | '__root__'
    | '/'
    | '/builds'
    | '/contact'
    | '/garage'
    | '/gear'
    | '/links'
    | '/partners'
    | '/racing'
    | '/results'
    | '/sponsors'
    | '/watch'
    | '/go/$partner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildsRoute: typeof BuildsRoute
  ContactRoute: typeof ContactRoute
  GarageRoute: typeof GarageRoute
  GearRoute: typeof GearRoute
  LinksRoute: typeof LinksRoute
  PartnersRoute: typeof PartnersRoute
  RacingRoute: typeof RacingRoute
  ResultsRoute: typeof ResultsRoute
  SponsorsRoute: typeof SponsorsRoute
  WatchRoute: typeof WatchRoute
  GoPartnerRoute: typeof GoPartnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racing': {
      id: '/racing'
      path: '/racing'
      fullPath: '/racing'
      preLoaderRoute: typeof RacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$partner': {
      id: '/go/$partner'
      path: '/go/$partner'
      fullPath: '/go/$partner'
      preLoaderRoute: typeof GoPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildsRoute: BuildsRoute,
  ContactRoute: ContactRoute,
  GarageRoute: GarageRoute,
  GearRoute: GearRoute,
  LinksRoute: LinksRoute,
  PartnersRoute: PartnersRoute,
  RacingRoute: RacingRoute,
  ResultsRoute: ResultsRoute,
  SponsorsRoute: SponsorsRoute,
  WatchRoute: WatchRoute,
  GoPartnerRoute: GoPartnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
